# Generated by Django 3.2.19 on 2024-06-08 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_listing_current_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='current_offer',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
