# Generated by Django 3.2.19 on 2024-06-11 17:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_listing_current_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='favorite',
            field=models.ManyToManyField(related_name='user_favorite', to=settings.AUTH_USER_MODEL),
        ),
    ]
